name: Build and Upload Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app (x64)
        run: npm run build:x64

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: 138.201.81.246
          username: root
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './out/make/squirrel.windows/x64/'
          remote_path: '/var/www/files/releases/microbot-launcher/'
          sftp_only: true
