name: Build and Upload

on:
  push:
    branches: [main]

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build:x64

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: microbot-launcher-exe-latest
          path: out/make/squirrel.windows/x64/*.exe

  upload:
    runs-on: ubuntu-latest
    needs: build-win

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: microbot-launcher-exe-latest
          path: ./artifact

      - name: Upload to Hetzner
        env:
          SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 138.201.81.246 >> ~/.ssh/known_hosts

          # Upload EXE
          scp ./artifact/*.exe root@138.201.81.246:/var/www/files/releases/microbot-launcher/microbot-launcher.exe

          # Upload additional files
          scp -r \
            ./css \
            ./images \
            ./libs \
            ./index.html \
            ./splash.html \
            ./renderer.js \
            ./jcef-bundle.zip \
            ./microbot-launcher.jar \
            root@138.201.81.246:/var/www/files/assets/microbot-launcher/
