name: Build/release

on: push

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18.17.1

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build:x64

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "1.1.1"
          prerelease: false
          title: "Release 1.1.1"
          files: |
             D:/a/Microbot-Launcher/Microbot-Launcher/out/squirrel.windows/microbot-launcher-x64-1.1.1 Setup.exe
