name: Build and Upload

on:
  push:
    branches: [main]

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run release

      - name: Upload Release as artifact
        uses: actions/upload-artifact@v4
        with:
          name: microbot-launcher-exe-latest
          path: |
            dist/* 
            !dist/**/

      - name: Upload project assets
        uses: actions/upload-artifact@v4
        with:
          name: microbot-launcher-assets
          path: |
            css/**
            images/**
            libs/**
            index.html
            renderer.js

  upload:
    runs-on: ubuntu-latest
    needs: build-win

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: microbot-launcher-exe-latest
          path: ./artifact

      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          name: microbot-launcher-assets
          path: ./assets

      - name: Upload to Hetzner
        env:
          SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 138.201.81.246 >> ~/.ssh/known_hosts

          # Clean up release folder before upload
          ssh root@138.201.81.246 'rm -rf /var/www/files/releases/microbot-launcher/*'

          # Upload EXE
          scp -r \
            ./artifact/* \
            root@138.201.81.246:/var/www/files/releases/microbot-launcher/

          # Upload additional files
          scp -r \
            ./assets/css \
            ./assets/images \
            ./assets/libs \
            ./assets/index.html \
            ./assets/renderer.js \
            root@138.201.81.246:/var/www/files/assets/microbot-launcher/
