name: CI

on:
    push:
        branches:
            - main
permissions:
  contents: write

jobs:
    build_windows:
        uses: ./.github/workflows/build-windows.yml

    build_linux:
        uses: ./.github/workflows/build-linux.yml

    build_mac:
        uses: ./.github/workflows/build-mac.yml

    release:
        needs: [build_windows, build_linux, build_mac]
        uses: ./.github/workflows/create-release.yml
        secrets: inherit # Pass secrets to the reusable workflow

    upload:
        needs: release
        uses: ./.github/workflows/upload-hetzner.yml
        secrets: inherit # Pass secrets to the reusable workflow
