name: Create Release

on:
    workflow_call:

permissions:
    contents: write

jobs:
    create-release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Get version from package.json
              id: version
              run: |
                  APP_VERSION=$(node -p "require('./package.json').version")
                  echo "version=$APP_VERSION" >> $GITHUB_OUTPUT
                  echo "App version: $APP_VERSION"

            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: ./artifacts

            - name: List downloaded files for debugging
              run: ls -R ./artifacts

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{ steps.version.outputs.version }}
                  name: Release v${{ steps.version.outputs.version }}
                  files: |
                      ./artifacts/microbot-launcher-exe-latest/*.exe
                      ./artifacts/microbot-launcher-exe-latest/latest.yml
                      ./artifacts/microbot-launcher-exe-latest/*.blockmap
                      ./artifacts/microbot-launcher-linux-latest/*.AppImage
                      ./artifacts/microbot-launcher-mac-latest/*.dmg
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
